### PR TITLE
Spring boot fixes

### PR DESCRIPTION
**Pull request by irbis**
netty.version should be set to 1.4.1.Final, otherwise not all jar files in the WEB-INF/lib and hello-ribbon doesn't run.

Method of initialization of bean RestTemplate should be fixed according of how it has to be used on SpringBoot 1.4.1.RELEASE.

### CODE REVIEW

**Comment by irbis** [comment]
Hi @iocanel
Could you please check my pull request? I'm finding this changes very useful.

**Comment by iocanel** [comment]
@irbis: Really useful indeed!

**Comment by iocanel** [comment]
Thank you very much!

**Comment by irbis** [comment]
You are welcome!

**Pull request merged**
