### PR TITLE
Align Spring-Cloud to CAMDEN.SR4 release with related dependencies too

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by oscerd** [comment]
Aligned and updated.

**Comment by oscerd** [comment]
Maybe we can release first and then merge this one @iocanel

**Comment by iocanel** [comment]
@oscerd: I will do so.

**Comment by oscerd** [comment]
Not sure here what's the problem with the build

**Comment by oscerd** [comment]
retest this please

**Comment by iocanel** [comment]
Seems like jenkins internall issues to me.

**Comment by oscerd** [comment]
retest this please

**Comment by oscerd** [comment]
@iocanel any idea here?

**Comment by iocanel** [comment]
@oscerd: not really! @rawlingsj: do you?

**Comment by jimmidyson** [comment]
Just an FYI I found out this morning... You'll need Spring cloud SR5 to work with Spring boot 1.5 when you upgrade that sometime.

**Comment by rawlingsj** [comment]
@oscerd @iocanel no real idea, this looks odd - I wonder if there was a bad config on the CD github org plugin at the time the PR was created.  Would you mind closing this PR and try again with a new one?

**Comment by oscerd** [comment]
@rawlingsj sure

**Pull request closed without merging**
